services:
  database:
    image: postgres:14
    networks:
      - appnet
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: goodPassword123
      POSTGRES_USER: admin
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"

  backend:
    image: backend-builder:latest
    build:
      context: ..
      dockerfile: docker/src/backend/Dockerfile
    container_name: backend
    ports:
      - "8081:8081"
    depends_on:
      - database
    networks:
      - appnet
    environment:
      DATABASE_URL: postgres://admin:goodPassword123@database:5432/myapp
    # volumes:
    #   - shared:/shared

  frontend:
    build:
      context: ..
      dockerfile: docker/src/frontend/Dockerfile
      # additional_contexts:
      #   backend: service:backend
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - appnet
    depends_on:
      - backend
    # volumes:
    #   - shared:/shared

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: on-failure
    networks:
      - appnet
    # env_file: ./secrets/.env
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9101:9101"
    networks:
      - appnet

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://admin:goodPassword123@postgres:5432/myapp?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - appnet

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:9.4.0
    restart: on-failure
    networks:
      - appnet
    environment:
      # - node.roles=data_content
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=true
      # - xpack.security.authc.api_key.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
      # - ./docker/src/elasticsearch:/usr/share/elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1

  elastic-init:
    image: curlimages/curl:latest
    depends_on:
      - elasticsearch
    volumes:
      - ./.secrets:/secrets
    entrypoint: >
      sh -c '
      until curl -s -u elastic:${ELASTIC_PASSWORD}
      http://elasticsearch:9200 >/dev/null; do
        echo "Waiting for Elasticsearch...";
        sleep 5;
      done;

      KIBANA_PASS=$$(openssl rand -base64 32)

      curl -X POST \
      -u elastic:${ELASTIC_PASSWORD} \
      -H "Content-Type: application/json" \
      http://elasticsearch:9200/_security/user/kibana_system/_password \
      -d "{\"password\":\"$$KIBANA_PASS\"}"

      echo "ELASTICSEARCH_USERNAME=kibana_system" > /secrets/kibana.env
      echo "ELASTICSEARCH_PASSWORD=$$KIBANA_PASS" >> /secrets/kibana.env

      echo "Kibana password generated."
      '

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:9.4.0
    restart: on-failure
    networks:
      - appnet
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_SYSTEM_PASSWORD}
    volumes:
      - kibana:/usr/share/kibana
    depends_on:
      - elastic-init

  logstash:
    container_name: logstash
    build:
      context: ..
      dockerfile: docker/src/logstash/Dockerfile
    image: custom-logstash:latest
    restart: on-failure
    networks:
      - appnet
    environment:
        - LS_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - esdata:/usr/share/logstash/data
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      # - ./pipeline:/usr/share/logstash/pipeline:ro
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:9.4.0
    container_name: docker_filebeat_1
    user: root
    volumes:
      - ${PWD}/docker/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/log/journal:/var/log/journal:ro
      - /run/log/journal:/run/log/journal:ro
      - /etc/machine-id:/etc/machine-id:ro
    command: ["filebeat", "-e", "--strict.perms=false"]
    depends_on:
      - logstash
    networks:
      - appnet

  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: on-failure
    networks:
      - appnet
    environment:
      GF_SERVER_ROOT_URL: http://localhost:3000
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: secret
      GF_AUTH_ANONYMOUS_ENABLED: "false"
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  grafana-storage:
  prometheus_data:
  esdata:
  kibana:
  # certs:
  # shared:

networks:
  appnet:
    driver: bridge