groups:
  - name: "Backend Alerts"
    folder: "Backend"
    interval: 60s
    rules:
      - alert: "BackendDown"
        expr: "up{job=\"backend\"} == 0"
        for: "5m"
        labels:
          severity: "critical"
        annotations:
          title: "Backend Service Down"
          summary: "Backend service is down"
          description: "The backend service ({{ $labels.instance }}) has been down for more than 5 minutes."

  - name: "Postgres Alerts"
    folder: "Posgres"
    interval: 60s
    rules:
      - alert: "PostgresDown"
        expr: "up{job=\"postgres\"} == 0"
        for: "5m"
        labels:
          severity: "critical"
        annotations:
          title: "Postgres Service Down"
          summary: "Postgres service is down"
          description: "The Postgres service ({{ $labels.instance }}) has been down for more than 5 minutes."

      - alert: "HighDatabaseErrors"
        expr: "rate(pg_stat_database_numbackends[5m]) > 10"
        for: "5m"
        labels:
          severity: "warning"
        annotations:
          title: "High Number of Database Connections"
          summary: "High number of database connections"
          description: "The Postgres service {{ $labels.instance }} has {{ $value }} active connections (threshold > 10)."
          runbook_url: "https://grafana.com/docs/grafana/latest/alerting/fire-alerts/"

  - name: "Node-metrics"
    folder: "Node Exporter"
    interval: 60s
    rules:
      - alert: HighDiskUsage
        expr: 100 - (node_filesystem_avail_bytes{device!="tmpfs", device!="rootfs"} / node_filesystem_size_bytes{device!="tmpfs", device!="rootfs"} * 100) > 90
        for: 5m
        labels:
          severity: "warning"
        annotations:
          title: "High Disk Usage"
          summary: "High disk usage detected"
          description: "Disk {{ $labels.device }} on instance {{ $labels.instance }} is {{ $value }}% full (threshold > 90%)."
          runbook_url: "https://grafana.com/docs/grafana/latest/alerting/fire-alerts/"

      - alert: CriticalDiskUsage
        expr: 100 - (node_filesystem_avail_bytes{device!="tmpfs", device!="rootfs"} / node_filesystem_size_bytes{device!="tmpfs", device!="rootfs"} * 100) > 95
        for: 5m
        labels:
          severity: "critical"
        annotations:
          title: "Critical Disk Usage"
          summary: "Critical disk usage detected"
          description: "Disk {{ $labels.device }} on instance {{ $labels.instance }} is {{ $value }}% full (threshold > 95%)."
          runbook_url: "https://grafana.com/docs/grafana/latest/alerting/fire-alerts/"

      - alert: HighCPULoad
        expr: node_load5 > 4
        for: 10m
        labels:
          severity: "critical"
        annotations:
          title: "High CPU Load"
          summary: "High CPU load detected"
          description: "CPU load on {{ $labels.instance }} is {{ $value }} (threshold > 4)."
          runbook_url: "https://grafana.com/docs/grafana/latest/alerting/fire-alerts/"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 90
        for: 5m
        labels:
          severity: "warning"
        annotations:
          title: "High Memory Usage"
          summary: "High memory usage detected"
          description: "Memory usage on {{ $labels.instance }} is {{ $value }}% (threshold > 90%)."
          runbook_url: "https://grafana.com/docs/grafana/latest/alerting/fire-alerts/"

      - alert: CriticalMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 95
        for: 5m
        labels:
          severity: "critical"
        annotations:
          title: "Critical Memory Usage"
          summary: "Critical memory usage detected"
          description: "Memory usage on {{ $labels.instance }} is {{ $value }}% (threshold > 95%)."
          runbook_url: "https://grafana.com/docs/grafana/latest/alerting/fire-alerts/"