path:
  logs: /usr/share/logstash/logs
xpack:
  monitoring:
    enabled: false
  logging:
    files:
      main:
        name: logstash-main.log
        path: /usr/share/logstash/logs
      slow:
        name: logstash-slow.log
        path: /usr/share/logstash/logs